# Generated by Django 4.0.3 on 2022-06-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldercare_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('work_time', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
